### ISSUE TITLE
Support templating

### ISSUE THREAD

**Issue by javierbrea** [mocks-server/main#411]
It is desirable to support "templates" when defining requests responses in some type of variants.

The templates should allow to access to request params, query and body, as well as [environments variables](#410). 

```yaml
- id: "get-user"
  url: "/api/users/:id"
  method: "GET"
  variants:
    - id: "success"
      type: "json"
      options:
        status: 200
        body:
          id: "{{req.params.id}}"
          name: "{{env.users[0].name}}"
```
